server:
  port: 9099

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/security-oauth-jwt?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  main:
    allow-bean-definition-overriding: true
  redis:
    database: 3
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000

security:
  ex-path: /swagger-resources/**,/swagger-ui.html,/v2/api-docs,/webjars/**,/user/register,/user/login,/user/refresh/token,/user/logout

enable:
  security: true

token:
  alive-time: 600
